### ISSUE TITLE
GUI clean up task list

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/freemocap#256]
- [x] add menu bar with basic functions
    - [x] new session
    - [x] load session
    - [x] reset to home screen
    - [ ] help (link to docs)
    - [ ] donate (link to donate
- [ ]  select session_id in new window after click "start session"
- [x] enable 'close cameras' button 
- [ ] link to a user survey on welcome screen
- [x] add 'load session' button to welcome screen
- [ ] add more text to 'alpha warning' text blurb on front page
- [ ] add `charuco board` option 
- [ ] add instructional blurb at top of each panel
- [x] Only create teh session folder when a video has been created
- [ ] copy `calibration.toml` to session folder when used
- [ ] separate 'calibration videos' from 'mocap videos' 
- [ ] remember settings across session
- [ ] disable buttons appropriately for a given session to avoid 
- [ ] remove paths from logs
