### ISSUE TITLE
Update Skelly Viewer

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#303]
# Tasks
- [x] Load first frame in skelly viewer
     - [x] Scale frame properly 
- [x] Skelly viewer can show sample data
- [x] host sample data somewhere

# Owner
Aaron

# Deadline
2023-02-24

**Comment by trentwirth** [comment]
Notes
- "first frame" => first frame of videos
- sample data needs to be hosted
  - lightweight
  - recording/picking data that already exists

**Comment by trentwirth** [comment]
Jon: first frame loads, but it doesn't scale properly. Good progress but needs to be fixed.
