### ISSUE TITLE
Improve Blender Output

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#307]
# Tasks
- [x] Flesh out Blender Mega-Script take2 (BMS_t2)
   - [x] Merge back on to full refactor 
   - [x] BMS_t2 has been integrated into the GUI
   - ~~Change so that empty marker data is driving Rig instead of meta-rig~~
   - [x] body
   - [x] Handle hands and face
- [x] Met with folks to offload work
- [x] Test Blender output (either ourselves, or give someone in the community our data to play with)
- [x] Clean up! (flesh out later)

# Owner
Jon `JSM`, Trent `TDW`, Philip `PQ`

# Deadline
2023-03-03
-> 2023-03-10
-> 2023-03-17

**Comment by trentwirth** [comment]
Notes
- Not where it needs to be for Jon to use it
- Jon is integrating ye ol' Blender Mega-Script
- should have some progress made by end of Feb 17 2023

Transform this card into: Improve Blender Output
- Flesh out Blender Mega-Script take2

- Post-processing towards the end of the standard freemocap process, somewhere we're loading raw data instead of post-processed. 
- So, this needs to be fixed
