### ISSUE TITLE
CaliCam MVP

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#313]
## Tasks
- [ ] Swap out CaliCam camera methods with SkellyCam (pair with Jon)
- [ ] Automate creation of inputs into bundle adjustment
- [ ] Frame by frame processing of 3D calibration, to select frame to use as origin
- [ ] UX Testing (pair with Trent)

## Owner
Mac

## Deadline
N/A
