### ISSUE TITLE
Fix Frame-Lag issue

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#314]
## Tasks
- [x] Meet with Endurance to figure out how to fix frame lag issue.
- [x] Fix the issue (loop structure), as identified by Endurance
- [x] Implement video saving aspects

## Owner
Jon

## Deadline
2023-02-28
