### ISSUE TITLE
Implent Automated Testing Suite Things

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#316]
## Tasks
- [ ] implement dummy test on jon/refactor branch
- [ ] implement "legit" tests on synchronization code
     - [ ] make sure sync code is pip installable
- [ ] implement legit tests in jon/refactor (or main)

## Owner
Philip
