### ISSUE TITLE
make new sample data for SkellyViewer

### ISSUE THREAD

**Issue by trentwirth** [freemocap/freemocap#329]
## Tasks
- [ ] record new (good :) )data
- [ ] put it on figshare
- [ ] integrate it with SkellyViewer

## Owner
Aaron

## Deadline
2023-03-08
